import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import { Mail, Shield, Bell, LogOut, User, TrendingUp, Target, CheckCircle2, RefreshCw } from "lucide-react";
import aiAvatar from "@/assets/ai-avatar.png";
export default function ProfilePage({ email, profile, onSignOut, onRefresh }) {
    const p = profile?.profile;
    const displayName = email.split("@")[0] || "User";
    const userType = p?.userType || "New User";
    const onboardingComplete = profile?.onboardingComplete ?? false;
    return (_jsx("div", { className: "h-full overflow-y-auto px-4 md:px-8 py-6", children: _jsxs("div", { className: "max-w-2xl mx-auto space-y-5", children: [_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, className: "flex flex-col items-center text-center", children: [_jsxs("div", { className: "relative", children: [_jsx("div", { className: "w-20 h-20 rounded-full overflow-hidden border-2 border-primary/40 shadow-glow", children: _jsx("img", { src: aiAvatar, alt: "ET AI", className: "w-full h-full object-cover" }) }), onboardingComplete && (_jsx("div", { className: "absolute -bottom-1 -right-1 w-6 h-6 rounded-full bg-emerald-500 border-2 border-background flex items-center justify-center", children: _jsx(CheckCircle2, { className: "w-3.5 h-3.5 text-white" }) }))] }), _jsx("h2", { className: "font-display text-2xl font-bold mt-4 capitalize", children: displayName }), _jsx("p", { className: "text-sm text-muted-foreground", children: email }), _jsx("span", { className: "mt-2 px-3 py-1 rounded-full text-xs font-medium bg-primary/10 text-primary border border-primary/20", children: userType }), onboardingComplete && (_jsx("span", { className: "mt-1 px-3 py-1 rounded-full text-xs font-medium bg-emerald-500/10 text-emerald-500 border border-emerald-500/20", children: "\u2713 Profile Complete" }))] }), p && (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.05 }, className: "bg-card border border-border rounded-2xl p-5 shadow-card", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx("h3", { className: "font-display text-base font-semibold", children: "Financial Profile" }), _jsx("button", { onClick: onRefresh, className: "p-1.5 rounded-lg hover:bg-muted transition-colors", children: _jsx(RefreshCw, { className: "w-4 h-4 text-muted-foreground" }) })] }), _jsx("div", { className: "space-y-3", children: [
                                { icon: User, label: "Profession", value: p.profession },
                                { icon: TrendingUp, label: "Experience", value: p.investmentExperience },
                                { icon: Target, label: "Risk Appetite", value: p.riskAppetite },
                                { icon: Shield, label: "Income Range", value: p.incomeRange },
                            ].filter(x => x.value).map((item, i) => (_jsxs("div", { className: "flex items-center gap-3 p-3 rounded-xl bg-muted", children: [_jsx("div", { className: "w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0", children: _jsx(item.icon, { className: "w-4 h-4 text-primary" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-[10px] text-muted-foreground font-medium uppercase tracking-wider", children: item.label }), _jsx("p", { className: "text-sm font-semibold capitalize", children: item.value })] })] }, i))) }), p.financialGoals && p.financialGoals.length > 0 && (_jsxs("div", { className: "mt-4", children: [_jsx("p", { className: "text-[10px] text-muted-foreground font-medium uppercase tracking-wider mb-2", children: "Financial Goals" }), _jsx("div", { className: "flex flex-wrap gap-2", children: p.financialGoals.map((goal, i) => (_jsx("span", { className: "px-3 py-1 rounded-full text-xs font-medium bg-primary/10 text-primary border border-primary/20", children: goal }, i))) })] }))] })), !p && (_jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, className: "bg-card border border-border rounded-2xl p-6 text-center shadow-card", children: _jsx("p", { className: "text-sm text-muted-foreground", children: "Complete the AI onboarding chat to build your profile." }) })), _jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.1 }, className: "bg-card border border-border rounded-2xl divide-y divide-border shadow-card", children: [
                        { icon: Mail, label: "Email Notifications", desc: "Receive daily market updates" },
                        { icon: Shield, label: "Privacy & Security", desc: "Manage your data preferences" },
                        { icon: Bell, label: "Push Notifications", desc: "Get alerts on price changes" },
                    ].map((item, i) => (_jsxs("button", { className: "w-full flex items-center gap-4 px-5 py-4 hover:bg-muted/50 transition-colors text-left", children: [_jsx("div", { className: "w-9 h-9 rounded-xl bg-muted flex items-center justify-center", children: _jsx(item.icon, { className: "w-4 h-4 text-muted-foreground" }) }), _jsxs("div", { className: "flex-1", children: [_jsx("p", { className: "text-sm font-medium", children: item.label }), _jsx("p", { className: "text-xs text-muted-foreground", children: item.desc })] })] }, i))) }), _jsxs(motion.button, { initial: { opacity: 0 }, animate: { opacity: 1 }, transition: { delay: 0.15 }, onClick: onSignOut, className: "w-full flex items-center justify-center gap-2 py-3 rounded-xl border border-destructive/30 text-destructive text-sm font-medium hover:bg-destructive/5 transition-colors", children: [_jsx(LogOut, { className: "w-4 h-4" }), "Sign Out"] })] }) }));
}
